### ISSUE TITLE
config.yml and RAG/Embedding processes

### ISSUE THREAD

**Issue by envolution** [meysamhadeli/codai#80]
Based on the repo instructions:
"codai requires a config.yml file in the root of your working directory or using environment variables to set below configs globally as a configuration."

Sadly the config.yml is being pushed to embedding, and causing unnecessary processing (since we know it's not really part of our project).  I suggest using a more unique name for this file, perhaps something like '.codai.config.yml' and ensuring the application ignores it while processing.  This way there is little chance of name clashes as well.

**Comment by Carl-Llewellyn** [comment]
> Based on the repo instructions: "codai requires a config.yml file in the root of your working directory or using environment variables to set below configs globally as a configuration."
> 
> Sadly the config.yml is being pushed to embedding, and causing unnecessary processing (since we know it's not really part of our project). I suggest using a more unique name for this file, perhaps something like '.codai.config.yml' and ensuring the application ignores it while processing. This way there is little chance of name clashes as well.

Have you not tried just adding the required flags to the existing yml?

**Comment by envolution** [comment]
> Have you not tried just adding the required flags to the existing yml?

I'm sorry mate, I don't think you red my comment

**Comment by meysamhadeli** [comment]
> Based on the repo instructions: "codai requires a config.yml file in the root of your working directory or using environment variables to set below configs globally as a configuration."
> 
> Sadly the config.yml is being pushed to embedding, and causing unnecessary processing (since we know it's not really part of our project). I suggest using a more unique name for this file, perhaps something like '.codai.config.yml' and ensuring the application ignores it while processing. This way there is little chance of name clashes as well.

Thanks for suggestion. it's true. config should not be part of embeddings or any process. I created a issue for that #82 and I will fix that in next version.

**Comment by Carl-Llewellyn** [comment]
> > Have you not tried just adding the required flags to the existing yml?
> 
> I'm sorry mate, I don't think you red my comment

Apology accepted

**Comment by meysamhadeli** [comment]
Implemented this requested issue #80 in PR #83
