### ISSUE TITLE
Chat doesn't seem aware of local files in the project using Nushell

### ISSUE THREAD

**Issue by rodrigomeireles** [meysamhadeli/codai#85]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/798ddaf1-f3eb-4c19-b8e5-927a6e8769b1">

The repository is non-empty and has some python files. It works fine on bash. I'm opening this issue and can help debug if you guide me.

**Comment by meysamhadeli** [comment]
Thanks for reporting this issue. seems it has trouble with md files! I will check to fix this issue.

**Comment by meysamhadeli** [comment]
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/39929801/386998085-798ddaf1-f3eb-4c19-b8e5-927a6e8769b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NjIzODIsIm5iZiI6MTczMTk2MjA4MiwicGF0aCI6Ii8zOTkyOTgwMS8zODY5OTgwODUtNzk4ZGRhZjEtZjNlYi00YzE5LWI4ZTUtOTI3YTZlODc2OWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDIwMzQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZTYyNjRhN2UzOTNmNGY4NGIxMzBiNzM1MTY1ZjQxMmQ1MTk1ZDNjZTkxYjU0ZmZhMDdlZjg0OTgxODQ2MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jYxs2SX-ik02C4BRQrLXqoao1yjrGS3xHyeleGQLAKI">
> The repository is non-empty and has some python files. It works fine on bash. I'm opening this issue and can help debug if you guide me.

@rodrigomeireles I had some small fixes in last version [v1.7.3](https://github.com/meysamhadeli/codai/releases/tag/v1.7.3) and now your problem should be fixed.
> Note: If you are using **RAG**, if in your input doesn't have enough keyword RAG doesn't reterive these files and you get error for example the file doesn't exist. For finding more ranging files you need to reduce the number `threshold` in config to `0.2` or `0.1`. (if we have bigger number for example `0.4` for threshold RAG need more key keyword in your input to finding relevant files.)
